test_switches:
  cap_mim_1p0fF_A_1p0:
    mim_option: "A"
    metal_level: "3LM"
    mim_cap: "1"
  cap_mim_1p0fF_B_4LM_1p0:
    mim_option: "B"
    metal_level: "4LM"
    mim_cap: "1"
  cap_mim_1p0fF_B_5LM_1p0:
    mim_option: "B"
    metal_level: "5LM"
    mim_cap: "1"
  cap_mim_1p0fF_B_6LM_1p0:
    mim_option: "B"
    metal_level: "6LM"
    mim_cap: "1"
  cap_mim_1p5fF_A_1p5:
    mim_option: "A"
    metal_level: "3LM"
    mim_cap: "1.5"
  cap_mim_1p5fF_B_4LM_1p5:
    mim_option: "B"
    metal_level: "4LM"
    mim_cap: "1.5"
  cap_mim_1p5fF_B_5LM_1p5:
    mim_option: "B"
    metal_level: "5LM"
    mim_cap: "1.5"
  cap_mim_1p5fF_B_6LM_1p5:
    mim_option: "B"
    metal_level: "6LM"
    mim_cap: "1.5"
  cap_mim_2p0fF_A_2p0:
    mim_option: "A"
    metal_level: "3LM"
    mim_cap: "2"
  cap_mim_2p0fF_B_4LM_2p0:
    mim_option: "B"
    metal_level: "4LM"
    mim_cap: "2"
  cap_mim_2p0fF_B_5LM_2p0:
    mim_option: "B"
    metal_level: "5LM"
    mim_cap: "2"
  cap_mim_2p0fF_B_6LM_2p0:
    mim_option: "B"
    metal_level: "6LM"
    mim_cap: "2"
