# SPDX-FileCopyrightText: Copyright 2026 GlobalFoundries PDK Authors
# SPDX-License-Identifier: Apache License 2.0
test_switches:
  nfet_10v0_asym:
    implicit_connect: true
  nfet_06v0:
    implicit_connect: true
  nfet_06v0_dn:
    consider_dn_dw_features: true
    implicit_connect: true
  nfet_05v0_dn :
    consider_dn_dw_features: true
    implicit_connect: true
  nfet_03v3:
    implicit_connect: true
  nfet_03v3_dn:
    consider_dn_dw_features: true
    implicit_connect: true
  nfet_06v0_nvt:
    implicit_connect: true
  pfet_05v0:
    implicit_connect: true
  pfet_10v0_asym:
    implicit_connect: true
  pfet_06v0:
    implicit_connect: true
  pfet_06v0_dn:
    consider_dn_dw_features: true
  pfet_03v3:
    implicit_connect: true
  pfet_03v3_dn:
    consider_dn_dw_features: true
  pfet_05v0_dn:
    consider_dn_dw_features: true
    implicit_connect: true
