# SPDX-FileCopyrightText: Copyright 2026 GlobalFoundries PDK Authors
# SPDX-License-Identifier: Apache License 2.0test_switches:
test_switches:
  sample_nfet_03v3:
    metal_top: "30K"
    mim_option: "A"
    metal_level: "3LM"
    poly_res: "1k"
    mim_cap: "2"
